### ISSUE TITLE
CeWL cewl_lib not in current dir

### ISSUE THREAD

**Issue by nitefood** [trustedsec/ptf#380] opened 2018-05-02 20:26 UTC
When running CeWL using the ptf-supplied launcher, you get an error because `./cewl_lib` is not found. The error doesn't happen if CeWL is ran from the directory where `cewl_lib` actually resides:

```
# cewl
CeWL 5.4.2 (Break Out) Robin Wood (robin@digi.ninja) (https://digi.ninja/)
Traceback (most recent call last):
        2: from /pentest/password-recovery/CeWL/cewl.rb:90:in `<main>'
        1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- ./cewl_lib (LoadError)

# locate cewl_lib
/pentest/password-recovery/CeWL/cewl_lib.rb
/usr/lib/ruby/vendor_ruby/cewl_lib.rb

# cd /pentest/password-recovery/CeWL/
# cewl
CeWL 5.4.2 (Break Out) Robin Wood (robin@digi.ninja) (https://digi.ninja/)

Missing URL argument (try --help)

#
```

**Comment by jeffmcjunkin** [comment] 2018-05-03 00:16
+1, confirmed today actually.

**Comment by jeffmcjunkin** [comment] 2018-06-01 17:10
Upstream patch submitted: https://github.com/digininja/CeWL/pull/38

**Comment by digininja** [comment] 2018-06-01 19:34
I've merged @jeffmcjunkin's PR so that should fix it for you.

**Comment by jeffmcjunkin** [comment] 2018-06-01 21:05
Thanks @digininja!

**Comment by jeffmcjunkin** [comment] 2018-06-07 12:57
This issue can be closed, since @digininja has the issue fixed in the upstream project.

**Closed** 2019-04-26 15:27 UTC
